#!/bin/bash
/home/orangepi/KUSC_2026-SBCC-Docs/DLLAMA/distributed-llama/dllama inference \
  --model models/llama3_1_8b_instruct_q40/dllama_model_llama3_1_8b_instruct_q40.m \
  --tokenizer models/llama3_1_8b_instruct_q40/dllama_tokenizer_llama3_1_8b_instruct_q40.t \
  --buffer-float-type q80 \
  --nthreads 2 \
  --max-seq-len 4096 \
  --prompt "Cellular respiration is a set of metabolic pathways that allow cells to convert energy stored in organic molecules into ATP. In eukaryotic cells, these processes occur in different cellular compartments and are tightly regulated based on environmental conditions. A team of researchers is investigating how oxygen availability affects ATP production and metabolic pathway usage in cultured animal cells. The researchers grow identical populations of cells under two different conditions: Condition 1 (Aerobic): Cells are supplied with abundant oxygen Condition 2 (Anaerobic): Cells are deprived of oxygen. The researchers measure ATP production, levels of metabolic intermediates, and enzyme activity over time. Their observations include the following: Under aerobic conditions, cells produce large amounts of ATP and show high activity of enzymes involved in the citric acid cycle and oxidative phosphorylation. Under anaerobic conditions, cells produce significantly less ATP overall. However, glycolysis rates increase, and lactate accumulates in the cells. The researchers observe that NAD+ levels decrease initially under anaerobic conditions but are later restored as lactate production increases. In a third experimental setup, the researchers add a chemical inhibitor that blocks the electron transport chain in cells that are otherwise supplied with oxygen. These cells show similar metabolic patterns to anaerobic cells. (a)  Describe the role of oxygen in cellular respiration. Include its function in the electron transport chain. (b) Explain why ATP production is lower under anaerobic conditions compared to aerobic conditions. (c) Describe how cells are able to continue producing ATP in the absence of oxygen. Include the role of NAD+. (d) Explain why lactate accumulates in cells under anaerobic conditions. (e) Using the observations from the inhibitor experiment, explain why blocking the electron transport chain leads to similar effects as oxygen deprivation. (f) Predict how the activity of the enzyme phosphofructokinase (PFK), a key regulatory enzyme in glycolysis, would change under anaerobic conditions" \
  --steps 975 \
  --workers 172.17.1.51:9999 172.17.1.52:9999 172.17.1.53:9999 \
  --temperature 0 \
  --seed 10042026
